#! /bin/bash
###############################################################################
# check prediction skill
#------------------------------------------------------------------------------
#
set -ex
MainScript=cheeck_Prognostic_SNR
if [ ! -f ${MainScript} ]; then
  cd ..
fi
ScriptHome=`pwd`
plotScript=${ScriptHome}/functions/Plotnc2D_Global_CA.m
fsuffix=".png"
#------------------------------------------------------------------------------
# Parameters (grep from the main script)
#------------------------------------------------------------------------------
OutputDIR=`grep "OutputDIR=" ${MainScript} | awk -F "=" '{print $NF}'`
thost=`echo $HOST | cut -c1-7 `
if [  "${thost}" == "hexagon" ]; then
  expCaseName=`echo ${OutputDIR} | awk -F "/" '{print $NF}'`
  DIR=/work/${USER}/SyncTransfer/${expCaseName}
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/dri/i915_dri.so:/usr/lib64/libstdc++.so.6
  #export LIBGL_DEBUG=verbose
fi
#ModelCompartments="lnd ocn atm ice"
ModelCompartments="ice"
mScript=`echo ${plotScript} | awk -F "/" '{print $NF}' | awk -F ".m" '{print $1}' `
MatlabScriptDIR=`echo ${plotScript} | awk -F "/${mScript}" '{print $1}'`

for ModelCompartment in ${ModelCompartments}; do 
# check for PPP only  
  PlotDIR=${DIR}/${ModelCompartment}/PPP_all_figures
  mkdir -p ${PlotDIR}

  PPPfiles=`ls ${DIR}/${ModelCompartment}/PPP_all_variables/*  `
  for PPPfile in ${PPPfiles}; do 
#    PPPfile=${DIR}/${ModelCompartment}/PPP_all_variables/PPP_ZWT.nc # for testing
    lonlat=`ncdump -h ${PPPfile} | grep "lat(" ` || lonlat=None
    if [ "${lonlat}" != "None" ]; then
      vname=`cdo showvar ${PPPfile} | cut -c2-100 `
      fname=`echo ${PPPfile} | awk -F "PPP_" '{print $NF}' | awk -F ".nc" '{print $1}'`
      figtarget=${PlotDIR}/PPP_${fname}${fsuffix}
      if [ ! -f ${figtarget} ]; then
        # define title
        varLongName=`ncdump -h ${PPPfile} | grep "${vname}:long_name" | awk -F "= "  '{print $NF}' | awk -F " ;" '{print $1}' `
        varunits=`ncdump -h ${PPPfile} | grep "${vname}:units" | awk -F "= "  '{print $NF}' | awk -F " ;" '{print $1}' `
        titleStr=${varLongName}" ("${varunits}")"
        titleStr=`echo "${titleStr//\"}" `
        echo ${PPPfile}
        cd ${MatlabScriptDIR}
        matlab -nosplash -nodesktop -r "vname='${vname}'; titleStr='${titleStr}'; filename='${PPPfile}'; ${mScript}; exit "
        PPPfilename=`echo ${PPPfile} | awk -F "/" '{print $NF}'`
        figfilename=`ls --color=no *${PPPfilename}*`
        #fsuffix=`echo ${figfilename} | tail -c5`
        cp -f ${figfilename} ${PlotDIR}/PPP_${fname}${fsuffix}
        rm -f ${figfilename}
      fi
    fi
  done
done

