#! /bin/bash
###############################################################################
# check prediction skill
#------------------------------------------------------------------------------
#
set -ex
MainScript=cheeck_Prognostic_SNR
if [ ! -f ${MainScript} ]; then
  cd ..
fi
ScriptHome=`pwd`
plotScript=${ScriptHome}/functions/Plotnc2D_Global_CA.m
fsuffix=".png"
#------------------------------------------------------------------------------
# Parameters (grep from the main script)
#------------------------------------------------------------------------------
OutputDIR=`grep "OutputDIR=" ${MainScript} | awk -F "=" '{print $NF}'`
thost=`echo $HOST | cut -c1-7 `
if [  "${thost}" == "hexagon" ]; then
  expCaseName=`echo ${OutputDIR} | awk -F "/" '{print $NF}'`
  DIR=/work/${USER}/SyncTransfer/${expCaseName}
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/dri/i915_dri.so:/usr/lib64/libstdc++.so.6
  #export LIBGL_DEBUG=verbose
fi
#ModelCompartments="lnd ocn atm ice"
ModelCompartments="ice"
mScript=`echo ${plotScript} | awk -F "/" '{print $NF}' | awk -F ".m" '{print $1}' `
MatlabScriptDIR=`echo ${plotScript} | awk -F "/${mScript}" '{print $1}'`

for ModelCompartment in ${ModelCompartments}; do 
# check for PPP only  
  PlotDIR=${DIR}/${ModelCompartment}/PPP_all_figures
  mkdir -p ${PlotDIR}

  PPPfiles=`ls ${DIR}/${ModelCompartment}/PPP_all_variables/*  `
  for PPPfile in ${PPPfiles}; do 
    #PPPfile=${DIR}/${ModelCompartment}/PPP_all_variables/PPP_All.micom.hm.sst.nc4 # for testing
    #lonlat=`ncdump -h ${PPPfile} | grep ":units" | grep -i "lon" ` || lonlat=None
    lonlat=`ncdump -h ${PPPfile} | grep "lon("  ` || lonlat=None
    # vname of lon & lat has to be checked and pass to matlab ...
    vname=`cdo -s -L showvar ${PPPfile} | cut -c2-100 `
    fname=`echo ${PPPfile} | awk -F "/" '{print $NF}' | awk -F "PPP" '{print $NF}' | awk -F ".nc" '{print $1}'`
    figtarget=${PlotDIR}/PPP${fname}${fsuffix}
    varLongName=`ncdump -h ${PPPfile} | grep "${vname}:long_name" | awk -F "= "  '{print $NF}' | awk -F " ;" '{print $1}' `
    varunits=`ncdump -h ${PPPfile} | grep "${vname}:units" | awk -F "= "  '{print $NF}' | awk -F " ;" '{print $1}' `
    titleStr=${varLongName}" ("${varunits}")"
    titleStr=`echo "${titleStr//\"}" `

    if [ "${ModelCompartment}" != "ocn" ] && [ "${ModelCompartment}" != "ice" ] ; then
      # [ "${lonlat}" == "None" ] is the case for ocn aice 
      if [ ! -f ${figtarget} ]; then
        # define title
        LonStr=`ncdump -h ${PPPfile} | grep ":units ="  | grep -i "lon" | awk -F ":" '{print $1}' `
        LatStr=`ncdump -h ${PPPfile} | grep ":units ="  | grep -i "lat" | awk -F ":" '{print $1}' `
        LonStr=${LonStr//\ }; LatStr=${LatStr//\ }
        echo ${PPPfile}
        cd ${MatlabScriptDIR}
        matlab -nosplash -nodesktop -r "LonStr='${LonStr}'; LatStr='${LatStr}';vname='${vname}'; titleStr='${titleStr}'; filename='${PPPfile}'; ${mScript}; exit "
        PPPfilename=`echo ${PPPfile} | awk -F "/" '{print $NF}'`
        figfilename=`ls --color=no *${PPPfilename}*`
        cp -f ${figfilename} ${PlotDIR}/PPP${fname}${fsuffix}
        rm -f ${figfilename}
      fi
    else
      if [ ! -f ${figtarget} ]; then
        # path has to be redirted to regrid path
        ana_path=`echo ${PPPfile} | awk -F "/PPP${fname}" '{print $1}'`
        ana_path=${ana_path}_regrided
        PPPfile_rg=`ls --color=no ${ana_path}/PPP${fname}.nc `
        LonStr=`ncdump -h ${PPPfile_rg} | grep ":units ="  | grep -i "lon" | awk -F ":" '{print $1}' `
        LatStr=`ncdump -h ${PPPfile_rg} | grep ":units ="  | grep -i "lat" | awk -F ":" '{print $1}' `
        LonStr=${LonStr//\ }; LatStr=${LatStr//\ }

        echo ${PPPfile}
        cd ${MatlabScriptDIR}
        matlab -nosplash -nodesktop -r "LonStr='${LonStr}'; LatStr='${LatStr}';vname='${vname}'; titleStr='${titleStr}'; filename='${PPPfile_rg}'; ${mScript}; exit "
        PPPfilename=`echo ${PPPfile} | awk -F "/" '{print $NF}'`
        figfilename=`ls --color=no *${PPPfilename}*`
        cp -f ${figfilename} ${PlotDIR}/PPP${fname}${fsuffix}
        rm -f ${figfilename}
      fi 
    fi
  done
done

