#! /bin/bash
###############################################################################
# ensemble info
#------------------------------------------------------------------------------
#
set -e
JobStartTime=`date`
JobName='ps_func_check_Signal2NoiseRatio'
# 
echo ${LinnBreaker}
echo ${LinnBreaker}
echo "Starting "${JobName}" of "${compartment}" ...... "

tempPrefix=t_'ps_func_check_Signal2NoiseRatio'
###############################################################################
tarDIR=${DIR}/${Mod}/PPP_all_variables
mkdir -p ${tarDIR}
PPPDIR=${DIR}/${Mod}/Signal2NoiseRatio
lsPPPStr="${PPPDIR}/*PPP*"
PPPfiles=`ls --color=no ${lsPPPStr} `
for PPPfile in ${PPPfiles}; do 
  PPPsuffix=`echo ${PPP_Rnc_suffix} | awk -F "PPP" '{print $NF}' | awk -F ".nc" '{print $1}' `
  FNprefix=PPP${PPPsuffix}_ 
  cdo -O splitvar ${PPPfile} ${tarDIR}/${FNprefix} 
done
cd ${tarDIR}
# check dimention and split levels
SVfiles=`ls --color=no ` # all splited variables 
for SVfile in ${SVfiles}; do 
  vname=`echo ${SVfile} | cut -c5-100 | awk -F ".nc" '{print $1}'`
  dimStr=`ncdump -h ${SVfile} | grep "${vname}(" | grep "," ` || dimStr="None"
  if [ "${dimStr}" == "None" ]; then
    rm ${SVfile}
  else
    nlevel=`cdo nlevel ${SVfile} `
    if [ "${nlevel}" != "1" ]; then
      fileprefix=`echo ${SVfile} | awk -F ".nc" '{print $1}' `
      cdo -O splitlevel ${SVfile} ${fileprefix}_
      rm ${SVfile}
    fi
  fi 
done

# remove insignificate results 
cd ${tarDIR}
SVfiles=`ls --color=no `
for SVfile in ${SVfiles}; do 
  NaN_check=`cdo -s outputf,%10.0f,1 -fldmin ${SVfile} | cut -c1-14`
  if [ ${NaN_check} -gt  1000 ] || [ ${NaN_check} -lt  -1000 ] ; then
    echo "No significant PPP for "${SVfile}", so we delete it."
    rm ${SVfile}
  else
    fldstatic=`cdo -s output -fldmax ${SVfile} `
    roundSkill=`echo "scale=0; (${fldstatic}*100)/1" | bc -l`  
    if [ "${roundSkill}" == "0" ]; then
      echo "Max PPP of "${SVfile}" is smaller than 0.001, so we delete it."
      rm ${SVfile}
    fi
  fi
done
###############################################################################
echo ${JobStartTime}
echo `date`" || "${JobName}
echo ${LinnBreaker}





