#! /bin/bash
###############################################################################
# ensemble info
#------------------------------------------------------------------------------
#
${DebugSetting}
JobStartTime=`date`
JobName='ps_func_check_Diff'
# 
echo ${LinnBreaker}
echo ${LinnBreaker}
echo "Starting "${JobName}" of "${compartment}" ...... "

tempPrefix=t_'ps_func_check_Diff'
###############################################################################
Mod=${compartment}
tarDIR=${DIR}/${Mod}/Diff
mkdir -p ${tarDIR}
for Member in ${Members}; do 
  mkdir -p ${tarDIR}/${Member}
done
cd ${DataDIR}/${firstMem}/${Mod}/hist
files=`ls --color=no ${prefix}*`
for file in ${files}; do
  . ${funcPath}/ps_func_check_filefix
  cd ${DataDIR}
  Sources=`ls ${DataDIR}/${casePrefix}*/${compartment}/hist/*${suffix}`
  ensmean=`ls ${DIR}/${Mod}/hist_ensmean/*${suffix} `
  for Source in ${Sources}; do
    filename=`echo ${Source} | awk -F "/" '{print $NF}'`
    caseName=`echo ${filename} | awk -F "${infix}" '{print $1}'`
    target=${tarDIR}/${caseName}/${filename}
    if [ ! -f ${target} ]; then
      echo "Checking "${filename}" of "${Mod}" ... "
      cdo sub ${Source} ${ensmean} ${target}
    fi
  done    
done
###############################################################################
echo ${JobStartTime}
echo `date`" || "${JobName}
echo ${LinnBreaker}





