#! /bin/bash
###############################################################################
# ensemble info
#------------------------------------------------------------------------------
#
set -e
JobStartTime=`date`
JobName='ps_func_check_Spread'
# 
tempPrefix=t_'ps_func_check_Spread'
###############################################################################
tarDIR=${DIR}/${Mod}/EnsDiffVar
mkdir -p ${tarDIR}
sqrDIR=${DIR}/${Mod}/sqr
if [ -d ${sqrDIR} ]; then
  cd ${sqrDIR}/${firstMem}
  files=`ls --color=no ${prefix}*`
else
  echo "Ensemble difference is not ready yet ... "
  exit 1
fi

for file in ${files}; do
  . ${funcPath}/ps_func_check_filefix
  cd ${sqrDIR}
  Sources=`ls */*${suffix} `
  target=${tarDIR}/${casePrefix}${infix}EnsDiffVar.${suffix}
  if [ ! -f ${target} ]; then
    echo "Checking "${suffix}" of "${Mod}" ... "
    cd ${sqrDIR}
    cdo ensmean ${Sources} ${target} 
  fi
done
target=${DIR}/${Mod}/Signal2NoiseRatio/${casePrefix}${infix}EnsDiffVar${suffix_no_year}
cdo -O ensmean ${tarDIR}/*${suffix_no_year}* ${target}
cdo -O griddes ${target} | grep "gridID" > ${tempDIR}/${tempPrefix}_grids
grid_count=` wc -l ${tempDIR}/${tempPrefix}_grids | awk -F " " '{print $1}'`
if [ "${grid_count}" != "1" ]; then
  cdo -O splitgrid ${target} ${target}_G 
fi
###############################################################################
echo ${JobStartTime}
echo `date`" || "${JobName}
echo ${LinnBreaker}





