#! /bin/bash
###############################################################################
target=${tarDIR}/${casePrefix}${infix}S2NR${S2NRsuffix}
cdo -O -b F64 copy ${EnsDiffVarFile} ${tempDIR}/${tempPrefix}_divisor 
cdo -O -b F64 copy ${file} ${tempDIR}/${tempPrefix}_dividend 
cdo -O div ${tempDIR}/${tempPrefix}_dividend ${tempDIR}/${tempPrefix}_divisor ${target}
target2=${tarDIR}/${casePrefix}${infix}PPP${S2NRsuffix}
cdo -O addc,1 ${target} ${tempDIR}/${tempPrefix}_divisor
cdo -O div ${target} ${tempDIR}/${tempPrefix}_divisor ${target2}

