#! /bin/bash
###############################################################################
# ensemble info
#------------------------------------------------------------------------------
#
${DebugSetting}
JobStartTime=`date`
JobName='ps_func_check_sqr'
# 
echo ${LinnBreaker}
echo ${LinnBreaker}
echo "Starting "${JobName}" of "${compartment}" ...... "

tempPrefix=t_'ps_func_check_sqr'
###############################################################################
tarDIR=${DIR}/${Mod}/sqr
VarName="SST"
for Member in ${Members}; do
  mkdir -p ${tarDIR}/${Member}
done
DiffDIR=${DIR}/${Mod}/Diff
if [ -d ${DiffDIR} ]; then
  cd ${DiffDIR}/${firstMem}
  files=`ls --color=no ${prefix}*`
else
  echo "Ensemble difference is not ready yet ... "
  exit 1
fi

for file in ${files}; do
  . ${funcPath}/ps_func_check_filefix
  cd ${DiffDIR}
  Sources=`ls */*${suffix} `
  for Source in ${Sources}; do

    filename=`echo ${Source} | awk -F "/" '{print $NF}' `
    caseName=`echo ${filename} | awk -F "${infix}" '{print $1}'`
    target=${tarDIR}/${caseName}/${filename}
    if [ ! -f ${target} ]; then
      echo "Checking "${filename}" of "${Mod}" ... "
      cdo -O  -f nc copy ${DiffDIR}/${Source} ${tempDIR}/${tempPrefix}_nc
      cdo sqr ${tempDIR}/${tempPrefix}_nc ${target} 
      rm -f ${tempDIR}/${tempPrefix}_nc*
    fi
  done
done

###############################################################################
echo ${JobStartTime}
echo `date`" || "${JobName}
echo ${LinnBreaker}





