#! /bin/bash
###############################################################################
# ensemble info
#------------------------------------------------------------------------------
#
${DebugSetting}
JobStartTime=`date`
JobName='ps_func_building_seansonal2decadal_average'
# 
echo ${LinnBreaker}
echo ${LinnBreaker}
echo "Starting "${JobName}" ...... "

tempPrefix=t_'ps_func_building_seansonal2decadal_average'
###############################################################################
# hs: DJF(12), MAM(3), JJA(6), SON(9)
# ho: one year 
# hf: 5 year
# hd: decadal 

O_infix=ho
Seasonal_pantad=`echo ${Seasonal_Decadal_pantad} | cut -c1-1`  ; S_infix=hs 
FiveYears_pantad=`echo ${Seasonal_Decadal_pantad} | cut -c2-2` ; F_infix=hf
Decadal_pantad=`echo ${Seasonal_Decadal_pantad} | cut -c3-3`   ; D_infix=hd
Mod=${compartment}
# for seasonal  
if [ "${Seasonal_pantad}" == "T" ]; then
  Smonths="03 06 09 12"
  for Sm1 in ${Smonths}; do 
    if [ "${Sm1}" = "03" ]; then Season=MAM; fi
    if [ "${Sm1}" = "06" ]; then Season=JJA; fi
    if [ "${Sm1}" = "09" ]; then Season=SON; fi
    if [ "${Sm1}" = "12" ]; then Season=DJF; fi
    for Member in ${Members}; do 
      cd ${DataDIR}/${Member}/${Mod}/hist
      files=`ls --color=no *-${Sm1}.nc`  || files=""
      for file in ${files}; do
        . ${funcPath}/ps_func_check_filefix
        fileLongPrefix=`echo ${file} | awk -F "${infix}" '{print $1}'`
        suff_infix=`echo ${infix} | tail -c4`
        pre_infix=`echo ${infix} | awk -F "${suff_infix}" '{print $1}'`
        New_infix=${pre_infix}${S_infix}. 
        targetFile=${fileLongPrefix}${New_infix}${fileyear}-${Season}.nc
        if [ ! -f ${targetFile} ]; then
          NextDate1=`python ${funcPath}/ps_func_datecheck.py ${fileyear} ${filemonth} 1 months 1 | cut -c1-7`
          NextDate2=`python ${funcPath}/ps_func_datecheck.py ${fileyear} ${filemonth} 1 months 2 | cut -c1-7`
          Nextfile1=`ls --color=no *${NextDate1}.nc` || Nextfile1="None"
          Nextfile2=`ls --color=no *${NextDate2}.nc` || Nextfile2="None"
          if [ -f ${Nextfile1} ] && [ -f ${Nextfile2} ] ; then
            ncea -O -3 ${file} ${Nextfile1} ${Nextfile2} -o ${targetFile} 
          fi
        fi
      done
    done # for diff members
  done # for diff months
fi

# for five years pantad
if [ "${FiveYears_pantad}" == "T" ] || [ "${Decadal_pantad}" == "T" ]; then
# indicate the need of annual averaged files
  for Member in ${Members}; do
    cd ${DataDIR}/${Member}/${Mod}/hist
    files=`ls --color=no *.????-??.nc` || files="None"
    if [ "${files}" != "None" ]; then
      for file in ${files}; do  
        . ${funcPath}/ps_func_check_filefix
        fileLongPrefix=`echo ${file} | awk -F "${infix}" '{print $1}'`
        suff_infix=`echo ${infix} | tail -c4`
        pre_infix=`echo ${infix} | awk -F "${suff_infix}" '{print $1}'`
        New_infix=${pre_infix}${O_infix}.
        targetFile=${fileLongPrefix}${New_infix}${fileyear}.nc
        if [ ! -f ${targetFile} ]; then
          files1=`ls --color=no *${infix}*${fileyear}*.nc `
          ensStr=""; month_count=0
          for infile in ${files1}; do 
            ensStr=${ensStr}" "${infile}
            (( month_count = month_count + 1 ))
          done
          if [ "${month_count}" == "12" ]; then 
            ncea -O -3 ${ensStr} -o ${targetFile}
          fi
        fi
      done      
    fi
  done
fi


if [ "${FiveYears_pantad}" == "T" ]; then
  for Member in ${Members}; do
    cd ${DataDIR}/${Member}/${Mod}/hist
    files=`ls --color=no *${O_infix}.????.nc` || files="None"
    firstyear=""; baseyear1=""; baseyear2=""
    if [ "${files}" != "None" ]; then
      for file in ${files}; do  
        . ${funcPath}/ps_func_check_filefix
        if [ "${firstyear}" == "" ]; then
          firstyear=${fileyear}
          (( baseyear1 = firstyear % 10 ))
          (( baseyear2 = baseyear1 + 5 ))
        fi

        (( fyrLastDG = fileyear % 10 ))
        if [ "${fyrLastDG}" == "${baseyear1}" ] || [ "${fyrLastDG}" == "${baseyear2}" ]; then
          fileLongPrefix=`echo ${file} | awk -F "${infix}" '{print $1}'`
          suff_infix=`echo ${infix} | tail -c4`
          pre_infix=`echo ${infix} | awk -F "${suff_infix}" '{print $1}'`
          New_infix=${pre_infix}${F_infix}.
          targetFile=${fileLongPrefix}${New_infix}${fileyear}.nc
          if [ ! -f ${targetFile} ]; then
            (( Nyr1 = fileyear + 1 ))
            (( Nyr2 = fileyear + 2 ))
            (( Nyr3 = fileyear + 3 ))
            (( Nyr4 = fileyear + 4 ))
            files1=`ls --color=no *${infix}*${fileyear}.nc `
            files2=`ls --color=no *${infix}*${Nyr1}.nc ` || file2="None"
            files3=`ls --color=no *${infix}*${Nyr2}.nc ` || file3="None"
            files4=`ls --color=no *${infix}*${Nyr3}.nc ` || file4="None"
            files5=`ls --color=no *${infix}*${Nyr4}.nc ` || file5="None"
            totalFiles=${files1}" "${files2}" "${files3}" "${files4}" "${files5}
            ensStr=""
            iHaveAllYears=1
            for tagfile in ${totalFiles}; do 
              if [ "${tagfile}" != "None" ]; then 
                ensStr=${ensStr}" "${tagfile}
              else
                iHaveAllYears=0
              fi
            done
            if [ "${iHaveAllYears}" == "1" ]; then
              ncea -O -3 ${ensStr}  -o ${targetFile}
            fi
          fi
        fi
      done
    fi
  done # for diff members
fi




###############################################################################
echo ${JobStartTime}
echo `date`" || "${JobName}
echo ${LinnBreaker}





