#! /bin/bash
###############################################################################
# ensemble info
#------------------------------------------------------------------------------
#
set -e
JobStartTime=`date`
JobName='ps_func_check_Signal2NoiseRatio'
# 
tempPrefix=t_'ps_func_check_Signal2NoiseRatio'
###############################################################################
tarDIR=${DIR}/${Mod}/Signal2NoiseRatio
EnsDiffVarDIR=${DIR}/${Mod}/EnsDiffVar
if [ -d ${EnsDiffVarDIR} ]; then
  cd ${DIR}/${Mod} 
  files=`ls --color=no ${casePrefix}*timvar*`
  ls --color=no ${casePrefix}*timvar* > ${tempDIR}/${tempPrefix}_files
  file_count=` wc -l ${tempDIR}/${tempPrefix}_files | awk -F " " '{print $1}'`
else
  echo "Ensemble difference is not ready yet ... "
  exit 1
fi

if [ "${file_count}" == "1" ]; then
  EnsDiffVar=`ls `
  echo ""
  exit 1
else
  for file in ${files}; do
    cd ${DIR}/${Mod} 
    GridC=`echo ${file} | awk -F "_G" '{print $NF}' | cut -c1-2`
    EnsDiffVarFile=`ls --color=no Signal2NoiseRatio/*EnsDiffVar*G${GridC}*` 
    ls --color=no Signal2NoiseRatio/*EnsDiffVar*G${GridC}* > ${tempDIR}/${tempPrefix}_files
    file_count=` wc -l ${tempDIR}/${tempPrefix}_files | awk -F " " '{print $1}'`
    if [ "${file_count}" == "1" ]; then
      S2NRsuffix=`echo ${EnsDiffVarFile} | awk -F "EnsDiffVar" '{print $NF}' `
      target=${tarDIR}/${prefix}S2NR${S2NRsuffix}
      cdo -O div ${EnsDiffVarFile} ${file} ${target}
      target2=${tarDIR}/${prefix}PPP${S2NRsuffix}
      cdo -O div ${target} -addc,1 ${target} ${target2}
    else
      echo "Unexpect file numbers: "${file_count}" ......"
      exit 1
    fi
  done
fi
###############################################################################
echo ${JobStartTime}
echo `date`" || "${JobName}
echo ${LinnBreaker}





