#! /bin/bash
###############################################################################
# ensemble info
#------------------------------------------------------------------------------
#
set -ex
JobStartTime=`date`
JobName=ps_func_check_SSTDiff
# 
tempPrefix=t_ps_func_check_SSTDiff
###############################################################################
Mod=${compartment}
tarDIR=${DIR}/${Mod}/Diff
mkdir -p ${tarDIR}
for Member in ${Members}; do 
  mkdir -p ${tarDIR}/${Member}
done
cd ${DataDIR}/${firstMem}/${Mod}/hist
files=`ls --color=no ${prefix}*`
for file in ${files}; do
  suffix=`echo ${file} | awk -F "${prefix}" '{print $NF}' `
  firstprefix=`echo ${prefix} | awk -F "." '{print $1}'`
  infix=`echo ${prefix} | awk -F "${firstprefix}" '{print $NF}'`

  cd ${DataDIR}
  Sources=`ls ${DataDIR}/${casePrefix}*/${compartment}/hist/*${suffix}`
  ensmean=`ls ${DIR}/${Mod}/hist_ensmean/*${suffix} `
  for Source in ${Sources}; do
    filename=`echo ${Source} | awk -F "/" '{print $NF}'`
    target=${tarDIR}/${Member}/${filename}
    if [ ! -f ${target} ]; then
      cdo sub ${Source} ${ensmean} ${target}
    fi
  done    
done


###############################################################################
echo ${JobStartTime}
echo `date`" || "${JobName}
echo ${LinnBreaker}





