#! /bin/bash
###############################################################################
# ensemble info
#------------------------------------------------------------------------------
#
${DebugSetting}
JobStartTime=`date`
JobName='ps_func_check_file_links'
# 
echo ${LinnBreaker}
echo ${LinnBreaker}
echo "Starting "${JobName}" ...... "

tempPrefix=t_'ps_func_check_file_links'
###############################################################################
# seasonal define
for compartment in ${ModelCompartments}; do
  for member in ${Members}; do
    DPath=${tempDIR}/DP/${member}/${compartment}/hist
    if [ ! -d ${DPath} ]; then
      mkdir -p ${DPath} ; cd ${DPath}
      ln -sf ${DataDDIR}/${member}/${compartment}/hist/* .
    fi
  done
done


###############################################################################
echo ${JobStartTime}
echo `date`" || "${JobName}
echo ${LinnBreaker}





