#! /bin/bash
###############################################################################
target=${tarDIR}/${casePrefix}${infix}S2NR${S2NRsuffix}
cdo -O -b F64 copy ${EnsDiffVarFile} ${tempDIR}/${tempPrefix}_divisor 
cdo -O -b F64 copy ${file} ${tempDIR}/${tempPrefix}_dividend 
# avoiding files with different number of variables
var_number_divisor=`cdo showvar ${tempDIR}/${tempPrefix}_divisor`
var_number_dividend=`cdo showvar ${tempDIR}/${tempPrefix}_dividend`
if [ "${var_number_divisor}" == "${var_number_dividend}" ]; then 
  cdo -O div ${tempDIR}/${tempPrefix}_dividend ${tempDIR}/${tempPrefix}_divisor ${target}
  target2=${tarDIR}/${casePrefix}${infix}PPP${S2NRsuffix}
  cdo -O addc,1 ${target} ${tempDIR}/${tempPrefix}_divisor
  cdo -O div ${target} ${tempDIR}/${tempPrefix}_divisor ${target2}
else
  #counting
  ivar_divisor=0; 
  for var in ${var_number_divisor}; do 
    (( ivar_divisor = ivar_divisor + 1 ))
  done
  ivar_dividend=0;
  for var in ${var_number_dividend}; do
    (( ivar_dividend = ivar_dividend + 1 ))
  done
  if [ "${ivar_divisor}" == "${ivar_dividend}" ]; then
    # sorting the vars 
    icount=1
    for var in ${var_number_dividend}; do 
      cdo -O selvar,${var} ${tempDIR}/${tempPrefix}_divisor ${tempDIR}/${tempPrefix}_var${icount}
      if [ "${icount}" == "1" ]; then
        cp -f ${tempDIR}/${tempPrefix}_var${icount} ${tempDIR}/${tempPrefix}_var
      else
        cdo -O merge ${tempDIR}/${tempPrefix}_var ${tempDIR}/${tempPrefix}_var${icount} ${tempDIR}/${tempPrefix}_varTotal
        cp -f ${tempDIR}/${tempPrefix}_varTotal ${tempDIR}/${tempPrefix}_var
      fi
      (( icount = icount + 1 ))
    done
    cp -f ${tempDIR}/${tempPrefix}_var ${tempDIR}/${tempPrefix}_divisor
    cdo -O div ${tempDIR}/${tempPrefix}_dividend ${tempDIR}/${tempPrefix}_divisor ${target}
    target2=${tarDIR}/${casePrefix}${infix}PPP${S2NRsuffix}
    cdo -O addc,1 ${target} ${tempDIR}/${tempPrefix}_divisor
    cdo -O div ${target} ${tempDIR}/${tempPrefix}_divisor ${target2}

  else
    echo "`date +%Y/%m/%d@%H:%M` :: Input streams have different number of variables per timestep" >> ${ErrorLogs}  
    echo "divisor: ${EnsDiffVarFile}" >> ${ErrorLogs}
    echo "dividend:  ${file}"  >> ${ErrorLogs}
  fi
fi
