#! /bin/bash
###############################################################################
# ensemble info
#------------------------------------------------------------------------------
#
${DebugSetting}
JobStartTime=`date`
JobName='ps_func_check_number_of_variables'
# 
echo ${LinnBreaker}
echo ${LinnBreaker}
echo "Starting "${JobName}" of "${compartment}" ...... "

tempPrefix=t_'ps_func_check_number_of_variables'
###############################################################################
Mod=${compartment}
tarDIR=${DIR}/${Mod}/Diff
# for getting infix
file=${prefix}
 . ${funcPath}/ps_func_check_filefix
echo "files to be checked: with infix ${infix}"
# check/re-check number of variables
SpreadDIR=${DIR}/${Mod}/Signal2NoiseRatio
if [ ! -d ${SpreadDIR} ]; then
  cd ${tarDIR}/${firstMem}
  VNCHKfiles=`ls --color=no *${infix}*`
else
  cd ${SpreadDIR}
  VNCHKfiles=`ls  *${infix}*EnsDiffVar*`
fi

sameVN=1
firstVNs=0
for VNCHKfile in ${VNCHKfiles}; do 
  # exclude grid_spliting files
  filecheck=`echo ${VNCHKfile}  | awk -F "_G" '{print $NF}' | cut -c3-5`
  if [ "${filecheck}" != ".nc" ]; then 
    if [ "${firstVNs}" == "0" ]; then 
      vnames1=`cdo showvar ${VNCHKfile} `;
      firstVNs=1 
    else
      vnames2=`cdo showvar ${VNCHKfile} `;
      if [ "${vnames1}" != "${vnames2}" ]; then
        sameVN=0
        break
      fi 
    fi
  fi
done
# define which variables have to be removed.  Stop if more than half of variables
inconsistentVNs=""
inconsistSuffixes=""
if [ "${sameVN}"  == "0" ]; then
  cd ${tarDIR}/${firstMem}
  VNCHKfiles=`ls --color=no ${prefix}*`
  firstVNs=0
  VNcount=0
  for VNCHKfile in ${VNCHKfiles}; do
    # find file suffix, which is going to be fixed 
    file=${VNCHKfile}
    . ${funcPath}/ps_func_check_filefix
    
    if [ "${firstVNs}" == "0" ]; then   
      vnames1=`cdo showvar ${VNCHKfile} `;
      firstVNs=1   
      for VN in ${vnames1}; do 
        (( VNcount = VNcount + 1 ))
      done
      halfVNcount=` echo "scale=0; (${VNcount})/2.0" | bc -l `
      echo "Number of variables in ${VNCHKfile} is ${VNcount}."
      inconsistSuffixes=${inconsistSuffixes}" "${suffix} 
    else
      vnames2=`cdo showvar ${VNCHKfile} `;
      if [ "${vnames1}" != "${vnames2}" ]; then
        VNcount2=0
        for VN2 in ${vnames2}; do
          (( VNcount2 = VNcount2 + 1 ))
        done

        if [ ${VNcount2} -lt ${VNcount}  ]; then
          tempVNs2=${vnames1}; tempVNs1=${vnames2} 
          VNcount=${VNcount2}
        else
          tempVNs1=${vnames1}; tempVNs2=${vnames2}
          inconsistSuffixes=${inconsistSuffixes}" "${suffix}
        fi
        for VN2 in ${tempVNs2}; do
set +x
          nomatch=1
          for VN1 in ${tempVNs1}; do
            if [ "${VN1}" == "${VN2}" ]; then
              nomatch=0
            fi
          done
set -x
          if [ "${nomatch}" == "1" ]; then
            VNcheck=`echo ${inconsistentVNs} | grep ${VN2}` || VNcheck="None"
            if [ "${VNcheck}" == "None" ]; then
              inconsistentVNs=${inconsistentVNs}" "${VN2}
            fi
          fi
        done

        vnames1=${tempVNs1}; 
        if [ ${VNcount} -lt ${halfVNcount} ]; then 
          echo "Losing more than half of variables ..."
          exit 5
        fi
      fi        
    fi
  done
fi
VN2bRemoved=`echo ${inconsistentVNs} | sed 's/\ /,/g'`
for suffix in ${inconsistSuffixes}; do 
  cd ${tarDIR}
  Sources=`ls ${casePrefix}*/*${suffix}`
  for Source in ${Sources}; do
    cdo -O delname,${VN2bRemoved} ${Source} ${tempDIR}/${tempPrefix}_nc
    cp -f ${tempDIR}/${tempPrefix}_nc ${Source} 
  done
done

###############################################################################
echo ${JobStartTime}
echo `date`" || "${JobName}
echo ${LinnBreaker}





