#! /bin/bash
###############################################################################
# regriding, and only for ice and ocn
#------------------------------------------------------------------------------
#
set -ex
MainScript=cheeck_Prognostic_SNR
scriptname=ps_func_micom_read_and_regriding_2Df.py
ModelCompartments="ocn"
if [ ! -f ${MainScript} ]; then
  cd ..
fi
ScriptHome=`pwd`
OutputDIR=`grep "OutputDIR=" ${MainScript} | awk -F "=" '{print $NF}'`
tempPrefix=t_'ps_func_split_variables_check_regrid'
thost=`echo $HOST | cut -c1-7 `
if [  "${thost}" == "hexagon" ]; then
  expCaseName=`echo ${OutputDIR} | awk -F "/" '{print $NF}'`
  DIR=/work/${USER}/SyncTransfer/${expCaseName}
  tempDIR=/work/earnest/temp 
else
  DIR=${OutputDIR}
  tempDIR=`grep "tempDIR=" ${MainScript} | awk -F "=" '{print $NF}'`
fi
funcPath=${ScriptHome}/functions

for ModelCompartment in ${ModelCompartments}; do
  if [ -d ${DIR}/${ModelCompartment}/PPP_all_variables ]; then
    tarDIR=${DIR}/${ModelCompartment}/PPP_all_variables
    tarDIRrg=${DIR}/${ModelCompartment}/PPP_all_variables_regrided
    if [ ! -d ${tarDIRrg} ]; then
      mkdir -p ${tarDIRrg}
    fi
    cp ${funcPath}/${scriptname} ${tempDIR} 
    cd ${tarDIR}
    PPPfiles=`ls --color=no `
    if [ "${ModelCompartment}" == "ocn" ]; then
      cp ${funcPath}/grid_g16.nc ${tempDIR}/grid.nc
    fi
    for PPPfile in ${PPPfiles}; do
      #PPPfile=PPP_All.micom.hm.sst.nc4  # for testing ...

      cd ${tempDIR}
      gridnumber=`ncdump -h ${tarDIR}/${PPPfile} | grep "latitude =" | awk -F " " '{print $3}' `
      if [ "${gridnumber}" != "181" ]; then
      nccopy -k 1 ${tarDIR}/${PPPfile} ${PPPfile} 
      vname=`cdo showvar ${PPPfile} | cut -c2-100 `
      fname=`echo ${PPPfile} | awk -F "PPP_" '{print $NF}' | awk -F ".nc" '{print $1}'`
      LonStr=`ncdump -h ${PPPfile} | grep ":long_name ="  | grep -i "longitude" | awk -F ":" '{print $1}' `  
      LatStr=`ncdump -h ${PPPfile} | grep ":long_name ="  | grep -i "latitude" | awk -F ":" '{print $1}' ` 
      if [ "${LonStr}" != "" ] && [ "${LatStr}" != "" ]; then
        is_using_local_grids=1
      elif [ "${LonStr}" != "" ] || [ "${LatStr}" != "" ]; then
        echo "Not horizontal map ..."
        is_do_nothing=1
      else
        is_using_local_grids=0
      fi
      tempFN=${tempDIR}/${tempPrefix}_output
      if [ "${is_do_nothing}" != "1" ]; then
        pythoncommandstr="${scriptname} ${PPPfile} ${tempFN} ${vname} ${is_using_local_grids} ${LonStr//\ } ${LatStr//\ }"
        ${pythoncommandstr}
      fi
      cp -f ${tempFN} ${tarDIRrg}/${PPPfile} 
    fi

    done
  fi
done



