#! /bin/bash
###############################################################################
# ensemble info
#------------------------------------------------------------------------------
#
set -ex
JobStartTime=`date`
JobName=ps_func_check_SSTDiff
# 
tempPrefix=t_ps_func_check_SSTDiff
###############################################################################

tarDIR=${DIR}/atm/Diff_SST
mkdir -p ${tarDIR}
cd ${DataDIR}/${casePrefix}_mem01/atm/hist
files=`ls --color=no *h0*`
for file in ${files}; do
  month=`echo $file | awk -F "-" '{print $NF}' | cut -c1-2 `
  year=`echo $file | awk -F "-" '{print $1}' | tail -c5 `
  echo ${year}-${month}
  cd ${DataDIR}
  suffix=`echo ${file} | awk -F "h0" '{print $2}' `
  Targets=`ls ${casePrefix}_mem??/atm/hist/*${suffix} `
  for target in ${Targets}; do
    tar_suffix=`echo ${target} | awk -F "${casePrefix}" '{print $NF}'  `
    date_suffix=`echo ${tar_suffix} | awk -F "h0" '{print $NF}' `
    ensfn=`ls ${DIR}/atm/hist/*_ensmean${date_suffix}` || ensfn="None"
    tarname=${tarDIR}/${casePrefix}_DiffSST${tar_suffix}
    if [ ! -f ${tarname} ]  && [ ${ensfn}!="None" ]; then
      cdo -L -O sub -selvar,SST ${target} -selvar,SST ${ensfn} ${tempDIR}/temp_nc
      cdo -O setvrange,-100,100 ${tempDIR}/temp_nc ${tarname}
    fi
  done
done


###############################################################################
echo ${JobStartTime}
echo `date`" || "${JobName}
echo ${LinnBreaker}





