#! /bin/bash
###############################################################################
# ensemble info
#------------------------------------------------------------------------------
#
${DebugSetting}
JobStartTime=`date`
JobName=ps_func_template
# 
echo ${LinnBreaker}
echo ${LinnBreaker}
echo "Starting "${JobName}" ...... "

tempPrefix=t_'ps_func_template'
###############################################################################
# check the files
cd ${DataDIR}/${firstMem}/${compartment}/hist
#tarFiles=`ls --color=no ${casePrefix}* `
tempcheck=`ls --color=no *${MEyear}* | awk -F "${MEyear}" '{print $1}'`



prefixes=""
is_same_prefix=0
if [ "${SkipOrigOutputs}" != "T" ]; then
  for prefixCheck in ${tempcheck}; do
    is_same_prefix=0
    for prefix in ${prefixes}; do
      if [ "${prefixCheck}" == "${prefix}" ]; then
        is_same_prefix=1
      fi
    done
    if [ "${is_same_prefix}" != "1" ]; then
      prefixes=${prefixes}" "${prefixCheck}
    fi
  done
else # if skiping original outputs
  for prefixCheck in ${tempcheck}; do
    is_same_prefix=0
    for prefix in ${prefixes}; do
      if [ "${prefixCheck}" == "${prefix}" ]; then
        realpath=`readlink -f ../hist/ | awk -F "hist" '{print $1}'`
        ls ${prefix}${MEyear}*  > ${tempDIR}/t_local_files
        thefilecount=`wc -l ${tempDIR}/t_local_files | awk -F " " '{print $1}'`
        thefile=`sed -n "${thefilecount}p" < ${tempDIR}/t_local_files `
        thepath=`readlink -f ${thefile}  | awk -F "hist" '{print $1}' `
        if [ "${realpath}" == "${thepath}" ]; then
          is_same_prefix=1
exit 55
        fi
      fi
    done
    if [ "${is_same_prefix}" != "1" ]; then
      prefixes=${prefixes}" "${prefixCheck}
    fi
exit 55
  done
fi


echo $prefixes
exit 55

###############################################################################
echo ${JobStartTime}
echo `date`" || "${JobName}
echo ${LinnBreaker}





