#! /bin/bash
###############################################################################
# generating web contant 
#------------------------------------------------------------------------------
#
set -ex
MainScript=cheeck_Prognostic_SNR
if [ ! -f ${MainScript} ]; then
  cd ..
fi
ScriptHome=`pwd`
webpageDIR=${ScriptHome}/docs
figureDIR=${ScriptHome}/figures
#------------------------------------------------------------------------------
# Parameters (grep from the main script)
#------------------------------------------------------------------------------
OutputDIR=`grep "OutputDIR=" ${MainScript} | awk -F "=" '{print $NF}'`

ModelCompartments="lnd ocn atm ice"
for ModelCompartment in ${ModelCompartments}; do 
  if [ -d ${OutputDIR}/${ModelCompartment}/PPP_all_figures ]; then
    rm -rf ${figureDIR}/PPP_${ModelCompartment}
    cp -rf ${OutputDIR}/${ModelCompartment}/PPP_all_figures ${figureDIR}/PPP_${ModelCompartment}
  fi
done

# -------------------------
# building base page in advance 
for ModelCompartment in ${ModelCompartments}; do
  MDfile=${webpageDIR}/PPP_${ModelCompartment}.markdown
  if [ ! -f ${MDfile} ]; then
    # header of markdown pages
    echo "PPP of all variables in "${ModelCompartment} > ${MDfile}
    echo "==========" >> ${MDfile} 
    echo ">> Created on: __"`date`"__ " >> ${MDfile} 
    echo ">> Last modified on: __"`date`"__ " >> ${MDfile}
  else
    nowdate=`date`
    sed -i s/"Last modified on: ".*/"Last modified on: __${nowdate}__ "/g ${MDfile}
  fi
  files=`ls --color=no ${OutputDIR}/${ModelCompartment}/PPP_all_variables/* `
  for file in ${files}; do 
    fldmax=0`cdo -s outputf,%10.3f,1 -fldmax ${file} | bc -l`
#      NaN_check=

      fldmean=0`cdo -s outputf,%10.3f,1 -fldmean ${file} | bc -l`
      SPGfldmax=0`cdo -s outputf,%10.3f,1 -fldmax -sellonlatbox,${SPGReg} ${file} | bc -l`
      EUfldmax=0`cdo -s outputf,%10.3f,1 -fldmax -sellonlatbox,${EUReg} ${file} | bc -l`
      Nino34fldmax=0`cdo -s outputf,%10.3f,1 -fldmax -sellonlatbox,${Nino34Reg} ${file} | bc -l`
      AltNino3fldmax=0`cdo -s outputf,%10.3f,1 -fldmax -sellonlatbox,${AtlNino3Reg} ${file} | bc -l`

exit 1

  done
done


cd ${figureDIR}
figureCount=0
fDIRs=`ls --color=no `
for fDIR in ${fDIRs}; do 
  Mod=`echo ${fDIR} | awk -F "PPP_" '{print $NF}'`
  ModfDIR=${figureDIR}/${fDIR}
  cd ${ModfDIR}
  figures=`ls --color=no `
  for figure in ${figures}; do 
  # check vname 
    (( figureCount = figureCount + 1 ))
    figsuffix=`echo ${figure} | tail -c5 `
    vname=`echo ${figure} | awk -F "PPP_" '{print $NF}' | awk -F "${figsuffix}" '{print $1}'`
    fname=`ls --color=no ${OutputDIR}/${Mod}/PPP_all_variables/*${vname}* `
    SPGReg="300,345,48,65"
    EUReg="40,140,40,70"
    Nino34Reg="-170,-120,-5,5"
    AtlNino3Reg="-20,-0,-3,3"
    if [ -f ${fname} ]; then 
      fldmax=0`cdo -s outputf,%10.3f,1 -fldmax ${fname} | bc -l`
#      NaN_check=

      fldmean=0`cdo -s outputf,%10.3f,1 -fldmean ${fname} | bc -l`
      SPGfldmax=0`cdo -s outputf,%10.3f,1 -fldmax -sellonlatbox,${SPGReg} ${fname} | bc -l`
      EUfldmax=0`cdo -s outputf,%10.3f,1 -fldmax -sellonlatbox,${EUReg} ${fname} | bc -l`
      Nino34fldmax=0`cdo -s outputf,%10.3f,1 -fldmax -sellonlatbox,${Nino34Reg} ${fname} | bc -l`
      AltNino3fldmax=0`cdo -s outputf,%10.3f,1 -fldmax -sellonlatbox,${AtlNino3Reg} ${fname} | bc -l`
    fi
sed -i s/"Total figures: ".*/"Total figures: ${figureCount}"/g ${ScriptHome}/README.md

exit 1
  done
done
