#! /bin/bash
###############################################################################
# generating web contant 
#------------------------------------------------------------------------------
#
set -ex
MainScript=cheeck_Prognostic_SNR
if [ ! -f ${MainScript} ]; then
  cd ..
fi
ScriptHome=`pwd`
fsuffix=`grep "fsuffix=" ${ScriptHome}/functions/plotingAll | awk -F "=" '{print $NF}'`
fsuffix=${fsuffix//\"}
#------------------------------------------------------------------------------
# Parameters (grep from the main script)
#------------------------------------------------------------------------------
ExpID=`grep "DataDIR=" ${MainScript} | awk -F "/" '{print $NF}'`
webpageDIR=${ScriptHome}/docs/${ExpID}
figureDIR=${ScriptHome}/figures/${ExpID}
SPGReg="300,345,48,65"
EUReg="40,140,40,70"
Nino34Reg="-170,-120,-5,5"
AtlNino3Reg="-20,-0,-3,3"
thPPP=0.6
OutputDIR=`grep "OutputDIR=" ${MainScript} | awk -F "=" '{print $NF}'`

ModelCompartments="lnd"
if [ ! -d ${webpageDIR} ]; then 
  mkdir -p ${figureDIR}
  mkdir -p ${webpageDIR}
fi
for ModelCompartment in ${ModelCompartments}; do 
  if [ -d ${OutputDIR}/${ModelCompartment}/PPP_all_figures ]; then
    rm -rf ${figureDIR}/PPP_${ModelCompartment}
    cp -rf ${OutputDIR}/${ModelCompartment}/PPP_all_figures ${figureDIR}/PPP_${ModelCompartment}
  fi
# -------------------------
# building base page in advance 
  figureCount=0
  MDfile=${webpageDIR}/PPP_${ModelCompartment}.markdown
  if [ ! -f ${MDfile} ]; then
    # header of markdown pages
    echo "PPP of all variables in "${ModelCompartment}" outputs" > ${MDfile}
    echo "==========" >> ${MDfile} 
    echo ">> Created on: __"`date`"__ " >> ${MDfile} 
    echo " "  >> ${MDfile}
    echo ">> Last updated on: __"`date`"__ " >> ${MDfile}
    echo "  * __Region (Lon,Lon,Lat,Lat)__ " >> ${MDfile}
    echo "  * SPG: (${SPGReg}) " >> ${MDfile}
    echo "  * Eurasia: (${EUReg}) " >> ${MDfile}
    echo "  * Nino 3.4: (${Nino34Reg}) " >> ${MDfile}
    echo "  * Atlantic Nino 3: (${AtlNino3Reg}) " >> ${MDfile}
    echo " "  >> ${MDfile}
    echo "------ "  >> ${MDfile}
    echo " "  >> ${MDfile}
  else
    nowdate=`date`
    sed -i s/"Last update".*/"Last updated on: __${nowdate}__ "/g ${MDfile}
    sed -i s/"SPG:".*/"SPG: (${SPGReg}) "/g ${MDfile}    
    sed -i s/"Eurasia:".*/"Eurasia: (${EUReg}) "/g ${MDfile}
    sed -i s/"Nino 3.4:".*/"Nino 3.4: (${Nino34Reg}) "/g ${MDfile}
    sed -i s/"Atlantic Nino 3:".*/"Atlantic Nino 3: (${AtlNino3Reg}) "/g ${MDfile}
  fi

  PPPfiles=`ls --color=no ${OutputDIR}/${ModelCompartment}/PPP_all_variables/* `
  for PPPfile in ${PPPfiles}; do 
    threholdPPP=`echo "scale=0; (${thPPP}*1000.0)/1.0" | bc -l `
    fldmax=0`cdo -s outputf,%10.3f,1 -fldmax ${PPPfile} | bc -l`
    NaN_check=`echo "scale=0; (${fldmax}*1000.0)/1.0" | bc -l | cut -c1-14`
    if [ ${NaN_check} -gt ${threholdPPP} ]; then 
      fldmax="__${fldmax}__"
    fi

    fldmean=0`cdo -s outputf,%10.3f,1 -fldmean ${PPPfile} | bc -l`
    NaN_check=`echo "scale=0; (${fldmean}*1000.0)/1.0" | bc -l | cut -c1-14`
    if [ ${NaN_check} -gt ${threholdPPP} ]; then
    fldmean="__${fldmean}__"
    fi

    SPGfldmax=0`cdo -s outputf,%10.3f,1 -fldmax -sellonlatbox,${SPGReg} ${PPPfile} | bc -l`
    NaN_check=`echo "scale=0; (${SPGfldmax}*1000.0)/1.0" | bc -l | cut -c1-14`
    if [ ${NaN_check} -gt 10000 ] || [ ${NaN_check} -lt -10000 ]; then
      SPGfldmax="NaN"
    else
      if [ ${NaN_check} -gt ${threholdPPP} ]; then
        SPGfldmax="__${SPGfldmax}__"
      fi
    fi


    EUfldmax=0`cdo -s outputf,%10.3f,1 -fldmax -sellonlatbox,${EUReg} ${PPPfile} | bc -l`
    NaN_check=`echo "scale=0; (${EUfldmax}*1000.0)/1.0" | bc -l | cut -c1-14`
    if [ ${NaN_check} -gt 10000 ] || [ ${NaN_check} -lt -10000 ]; then
      EUfldmax="NaN"
    else
      if [ ${NaN_check} -gt ${threholdPPP} ]; then
        EUfldmax="__${EUfldmax}__"
      fi
    fi

    Nino34fldmax=0`cdo -s outputf,%10.3f,1 -fldmax -sellonlatbox,${Nino34Reg} ${PPPfile} | bc -l`
    NaN_check=`echo "scale=0; (${Nino34fldmax}*1000.0)/1.0" | bc -l | cut -c1-14`
    if [ ${NaN_check} -gt 10000 ] || [ ${NaN_check} -lt -10000 ]; then
      Nino34fldmax="NaN"
    else
      if [ ${NaN_check} -gt ${threholdPPP} ]; then
        Nino34fldmax="__${Nino34fldmax}__"
      fi
    fi
 
    AltNino3fldmax=0`cdo -s outputf,%10.3f,1 -fldmax -sellonlatbox,${AtlNino3Reg} ${PPPfile} | bc -l`
    NaN_check=`echo "scale=0; (${AltNino3fldmax}*1000.0)/1.0" | bc -l | cut -c1-14`
    if [ ${NaN_check} -gt 10000 ] || [ ${NaN_check} -lt -10000 ]; then
      AltNino3fldmax="NaN"
    else
      if [ ${NaN_check} -gt ${threholdPPP} ]; then
        AltNino3fldmax="__${AltNino3fldmax}__"
      fi
    fi
    # update markdown data ...
    vname=`cdo showvar ${PPPfile} | cut -c2-100 `
    namesuffix=`echo ${PPPfile} | awk -F "/" '{print $NF}' | awk -F "${vname}" '{print $NF}' | awk -F ".nc" '{print $1}'` 
    nameinfix=`echo ${PPPfile} | awk -F "/" '{print $NF}' | awk -F "${vname}" '{print $1}' | awk -F "PPP" '{print $NF}' | cut -c2-100`

    varLongName=`ncdump -h ${PPPfile} | grep "${vname}:long_name" | awk -F "= "  '{print $NF}' | awk -F " ;" '{print $1}' `
    varLongName=`echo ${varLongName//\"} | tr "/" "-"`
    vnameCheck=`grep "${varLongName}" ${MDfile} | grep "${levelStr}" | grep "${nameinfix}" ` || vnameCheck="None"

    figurelink=""
    levelStr=""
    if [ "${namesuffix}" != "" ]; then
      level=`echo ${namesuffix} | cut -c2-100`
      levelStr="(level: ${level})"

    else
      levelStr="(level: 0)"
    fi

    if [ -d ${figureDIR}/PPP_${ModelCompartment} ]; then
      cd ${figureDIR}/PPP_${ModelCompartment}
      echo "${vname}${nameinfix}${fsuffix}"
      figfilename=`ls *${nameinfix}${vname}${fsuffix} ` || figfilename="None"

      if [ "${figfilename}" == "None" ]; then
        figurelink=""
      else
        (( figureCount = figureCount + 1 ))
        if [ "${levelStr}" == "(level: 0)" ]; then 
          figurelink=" ![] (../../figures/${ExpID}/PPP_${ModelCompartment}/${figfilename})"
        fi
      fi
    fi

    if [ "${vnameCheck}" == "None" ]; then
      # generate the line
#      echo "  * __${vname}: ${varLongName}__, ${nameinfix}, ${levelStr} -> maximum PPP is ${fldmax}; averaged PPP is ${fldmean}; maximum PPP of SPG is ${SPGfldmax}; maximum PPP of Eurasia is ${EUfldmax}; maximum PPP of Nino 3 is ${Nino34fldmax}; maximum PPP of Atlantic Nino 3 is ${AltNino3fldmax} ${figurelink}" >> ${MDfile}
      echo "  * __${vname}: ${varLongName}__, ${nameinfix}, ${levelStr} -> maximum PPP is ${fldmax}; averaged PPP is ${fldmean} ${figurelink}" >> ${MDfile}
      echo " " >> ${MDfile}
      echo "------ "  >> ${MDfile}
      echo " " >> ${MDfile}
    else
      figurelink=`echo ${figurelink} | sed 's/\//\\\\\//g' `
#      sed -i s/"${vname}: ${varLongName}__, ${nameinfix}, ${levelStr} -".*/"${vname}: ${varLongName}__, ${nameinfix}, ${levelStr} -> maximum PPP is ${fldmax}; averaged PPP is ${fldmean}; maximum PPP of SPG is ${SPGfldmax}; maximum PPP of Eurasia is ${EUfldmax}; maximum PPP of Nino 3 is ${Nino34fldmax}; maximum PPP of Atlantic Nino 3 is ${AltNino3fldmax} ${figurelink}"/g ${MDfile}
sed -i s/"${vname}: ${varLongName}__, ${nameinfix}, ${levelStr} -".*/"${vname}: ${varLongName}__, ${nameinfix}, ${levelStr} -> maximum PPP is ${fldmax}; averaged PPP is ${fldmean} ${figurelink}"/g ${MDfile}
    fi

#  mlscheck=`grep "fice" ${PPPfile} `  || mlscheck="None"
#  if [ "${mlscheck}" != "None" ] &&  [ "${nameinfix}" == "02.micom.hm." ] ; then 
#    exit 5 
#  fi 

  done
  sed -i s/"total figures in ${ModelCompartment} (${ExpID}): ".*/"total figures in ${ModelCompartment} (${ExpID}): __${figureCount}__"/g ${ScriptHome}/docs/FrontPage_${ExpID}.markdown
done

