#! /bin/ksh
###############################################################################
# check the signal to noise ratio  
#------------------------------------------------------------------------------
set -e
ScriptHome=`pwd`
#------------------------------------------------------------------------------
# Parameters
#------------------------------------------------------------------------------
DIR=/scratch/earnest/SyncTransfer/FF_ini_try
tempDIR=/scratch/earnest/temp
casePrefix=NorCPM_F19_tn21
MEyear=2000
DataDIR=/scratch/earnest/noresmexp/FF_ini_try

ModelCompartments="ocn atm ice lnd"
#------------------------------------------------------------------------------
# Constants
is_revisiting_jobs=1
#------------------------------------------------------------------------------
funcPath=${ScriptHome}/functions
LinnBreaker="--------------------------------------------------------"
#------------------------------------------------------------------------------
#
if [ ! -d ${DIR} ]; then
  mkdir -p ${DIR}
fi
cd ${DataDIR}
Members=`ls --color=no `
firstMem=`echo ${Members} | awk -F " " '{print $1}'`
lastMem=`echo ${Members} | awk -F " " '{print $NF}'`

set -ex 

for compartment in ${ModelCompartments}; do 
  # check the files
  cd ${DataDIR}/${firstMem}/${compartment}/hist
  #tarFiles=`ls --color=no ${casePrefix}* `
  tempcheck=`ls --color=no *${MEyear}* | awk -F "${MEyear}" '{print $1}'`

  prefixes=""
  is_same_prefix=0
  for prefixCheck in ${tempcheck}; do 
    is_same_prefix=0
    for prefix in ${prefixes}; do 
      if [ "${prefixCheck}" == "${prefix}" ]; then
        is_same_prefix=1
      fi
    done
    if [ "${is_same_prefix}" != "1" ]; then
      prefixes=${prefixes}" "${prefixCheck}
    fi
  done

  #---------------------------------------------------------------------------
  for prefix in ${prefixes}; do 
    . ${funcPath}/ps_func_building_ensemble_mean
  done

exit 1
  for prefix in ${refixes}; do 
    
  cd ${DIR}  
  if [ "${is_building_ensemble_mean}" == "1" ]; then
    . ${funcPath}/ps_func_building_ensemble_mean
  fi
  done
done

if [ "${is_revisiting_jobs}" == "1" ]; then
    . ${funcPath}/ps_func_revisiting_jobs
fi


