#! /bin/bash
###############################################################################
# check prediction skill
#------------------------------------------------------------------------------
#
set -ex
ScriptHome=`pwd`
MainScript=cheeck_Prognostic_SNR
plotScript=${ScriptHome}/functions/Plotnc2D_Global_CA.m

#------------------------------------------------------------------------------
# Parameters (grep from the main script)
#------------------------------------------------------------------------------
OutputDIR=`grep "OutputDIR=" ${MainScript} | awk -F "=" '{print $NF}'`
thost=`echo $HOST | cut -c1-7 `
if [  "${thost}" == "hexagon" ]; then
  expCaseName=`echo ${OutputDIR} | awk -F "/" '{print $NF}'`
  DIR=/work/${USER}/SyncTransfer/${expCaseName}
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/dri/i915_dri.so:/usr/lib64/libstdc++.so.6
  #export LIBGL_DEBUG=verbose
fi
#ModelCompartments="lnd ocn atm ice"
ModelCompartments="lnd"
mScript=`echo ${plotScript} | awk -F "/" '{print $NF}' | awk -F ".m" '{print $1}' `
MatlabScriptDIR=`echo ${plotScript} | awk -F "/${mScript}" '{print $1}'`
for ModelCompartment in ${ModelCompartments}; do 
# check for PPP only  
  PlotDIR=${DIR}/${ModelCompartment}/PPP_all_figures
  mkdir -p ${PlotDIR}

  PPPfiles=`ls ${DIR}/${ModelCompartment}/PPP_all_variables/*  `
  for PPPfile in ${PPPfiles}; do 
#    PPPfile=${DIR}/${ModelCompartment}/PPP_all_variables/PPP_ZWT.nc # for testing
    vname=`cdo showvar ${PPPfile} | cut -c2-100 `
    fname=`echo ${PPPfile} | awk -F "PPP_" '{print $NF}' | awk -F ".nc" '{print $1}'`
    echo ${PPPfile}
    cd ${MatlabScriptDIR}
    matlab -nosplash -nodesktop -r "vname='${vname}'; filename='${PPPfile}'; ${mScript}; exit "
    PPPfilename=`echo ${PPPfile} | awk -F "/" '{print $NF}'`
    figfilename=`ls --color=no *${PPPfilename}*`
    fsuffix=`echo ${figfilename} | tail -c5`
    cp -f ${figfilename} ${PlotDIR}/PPP_${fname}${fsuffix}
  done
done

